Added new custom eslint rule to fix wallaby comments
checkdigit/eslint-plugin pull request #42
Opened 2023-10-24 19:12 UTC by jpolavar

Closes #29. Removes  wallaby-specific temporary comments like // ?. and // file.only

2023-10-26 17:17 UTC, carlansley requested changes
A few changes.  Another question, has this been tested on any of our code bases?  I don't see a beta of eslint-config that has this rule included.

2023-10-26 17:17 UTC, carlansley commented on .DS_Store
this file shouldn't be in the PR

2023-10-26 17:17 UTC, carlansley commented on src/no-wallaby-comment.spec.ts
> +        output: `const NOT_A_SECRET = "A template that isn't a secret."; `,
i think the fix should remove all extra space from the end of the line

2023-10-26 17:17 UTC, carlansley commented on src/no-wallaby-comment.spec.ts
> +        output: ` const NOT_A_SECRET = "A template that isn't a secret.";   `,
same here

2023-10-26 17:17 UTC, carlansley commented on src/no-wallaby-comment.spec.ts
> +const LINE_WITH_COMMENT = `const NOT_A_SECRET = "A template that isn't a secret."; // ?`;
there's no test for `file.only`, and also i think there should be single comment tests for the various varieties (e.g. `// ?.` etc)

2023-10-26 17:19 UTC, carlansley commented
`file.skip` is another comment we're not dealing with here, there may be others also

2023-11-01 18:04 UTC, carlansley requested changes

2023-11-01 18:04 UTC, carlansley commented on src/no-wallaby-comment.spec.ts
> +// file.skip const NOT_A_SECRET = "A template that isn't a secret.";
file.skip and file.only are normally on lines by themselves, not in front of commented code.  think we need to test that scenario instead (tbh not sure what Wallabys behavior is here)

2023-11-01 18:06 UTC, carlansley commented on src/no-wallaby-comment.ts
> +      const parts = line.split(regex);
has this been fixed/dealt with?  its unclear to me

2023-11-01 18:08 UTC, carlansley commented
have you tried this on one of our larger internal repos?  Think it's worth trying, especially to make sure the regex is performant.

2023-11-01 18:53 UTC, jpolavar commented on src/no-wallaby-comment.ts
> +      const parts = line.split(regex);
It was previous commit. It was fixed and we don't that specific functionality of splitting and regex in the latest commit

2023-11-02 14:18 UTC, carlansley requested changes
i played around with wallaby's comment system, noticed the following all work:
```
//       file.only

/* file.only    */

/*
 * file.only
 */
 
 /*
 * some other comment
 * file.skip
 */
```

i'm thinking we should make sure all of these various situations are identified/tested

2023-11-06 17:31 UTC, jpolavar commented
> i played around with wallaby's comment system, noticed the following all work:
> 
> ```
> //       file.only
> 
> /* file.only    */
> 
> /*
>  * file.only
>  */
>  
>  /*
>  * some other comment
>  * file.skip
>  */
> ```
> 
> i'm thinking we should make sure all of these various situations are identified/tested
Tested different scenarios on aws-nock and test cases as well to the library

2023-11-08 21:00 UTC, carlansley requested changes

2023-11-09 14:11 UTC, carlansley approved these changes

2023-11-21 15:07 UTC, merged