Fixed to allow simple text-only regexs to not have a comment
checkdigit/eslint-plugin pull request #71
Opened 2024-07-03 18:39 UTC by jpolavar

Closes #68

2024-07-03 20:11 UTC, jpolavar commented
tested on monitor service 
![Uploading Screenshot 2024-07-03 at 3.07.24 PM.png…]()

2024-07-09 19:00 UTC, carlansley requested changes

2024-07-09 19:00 UTC, carlansley commented on src/regular-expression-comment.ts
> +          if (!isSimpleTextPattern) {
i think it would be better to do a `if (isSimpleTextPattern)` and just return.  makes the diff easier to follow too.

2024-07-09 19:09 UTC, carlansley approved these changes

2024-07-09 19:10 UTC, merged