add new rule require-resolve-full-response
checkdigit/eslint-plugin pull request #77
Opened 2024-09-23 17:21 UTC by le-cong

Fixes #76

2024-09-24 20:16 UTC, carlansley requested changes

2024-09-24 20:16 UTC, carlansley commented on src/ts-tester.test.ts
is this used anywhere?  if it is, the comment on the first line has the wrong path

2024-09-24 20:16 UTC, carlansley commented on ts-init/file.ts
needed?

2024-09-24 20:16 UTC, carlansley commented on ts-init/react.tsx
needed?

2024-09-25 19:26 UTC, le-cong commented on ts-init/file.ts
somehow typescript-eslint requires physical present of this empty file to work, i haven't found any workaround to make it work otherwise. hopefully a better option can be available in the future.

2024-09-25 19:26 UTC, le-cong commented on ts-init/react.tsx
it seems still working without this empty file, so deleting it

2024-10-03 15:05 UTC, carlansley approved these changes

2024-10-03 15:29 UTC, jpolavar approved these changes

2024-10-03 15:32 UTC, merged