new rules - require-fixed-services-import and no-duplicated-imports
checkdigit/eslint-plugin pull request #86
Opened 2024-10-07 19:26 UTC by le-cong

fixes #85

2024-10-10 19:52 UTC, carlansley requested changes
lgtm, except I'm not sure what the difference is between `checkdigit/no-duplicated-imports` and the existing `no-duplicate-imports`

2024-10-10 19:52 UTC, carlansley commented on docs/rules/no-duplicated-imports.md
How does this rule differ from https://eslint.org/docs/latest/rules/no-duplicate-imports?

2024-10-10 20:04 UTC, le-cong commented on docs/rules/no-duplicated-imports.md
they only report issue, but we take action to autofix (merge) them. this will reduce some manual fixes especially for services importing multiple entries for different dependent service typings.

2024-10-10 21:05 UTC, carlansley commented on docs/rules/no-duplicated-imports.md
so we should disable the ESLint one in eslint-config when it's updated to use this rule?  Or does the standard rule do other stuff?

2024-10-11 17:39 UTC, carlansley approved these changes
lftm.  one request - we keep track of disabling the standard eslint version of the `no-duplicated-import` rule somewhere in an issue in https://github.com/checkdigit/eslint-config

2024-10-19 00:50 UTC, le-cong commented
sorry, please review again. had to merge with the latest v7 with eslint9 upgrade.

2024-10-21 20:26 UTC, carlansley requested changes
One super-minor thing, otherwise lftm

2024-10-21 20:26 UTC, carlansley commented on package.json
>      "@checkdigit/typescript-config": "8.0.0",
missing `^`

2024-10-22 02:12 UTC, le-cong commented on docs/rules/no-duplicated-imports.md
our rule is little automated than the eslint core rule which don't do much else. and sure we can disable the core one when we update eslint-config

2024-10-23 14:55 UTC, carlansley approved these changes

2024-10-23 15:28 UTC, merged