ban the usage of Endpoint type
checkdigit/eslint-plugin pull request #93
Opened 2024-11-07 20:06 UTC by le-cong

Fixes #92

2024-11-18 19:27 UTC, carlansley approved these changes

2024-11-19 17:14 UTC, le-cong commented
sorry, can you re-approve due to conflict merge?

2024-11-20 16:11 UTC, carlansley requested changes
lftm, just a dep thing

2024-11-20 16:11 UTC, carlansley commented on package.json
> +    "debug": "^4.3.7",
i don't see this being used anywhere

2024-11-20 16:11 UTC, carlansley commented on package.json
> +    "@types/debug": "^4.1.12",
this also

2024-11-20 17:57 UTC, carlansley approved these changes

2024-11-20 17:57 UTC, merged